import type { Metadata } from "next";
// import { Geist, Geist_Mono, Sans } from "next/font/google";
import "./globals.css";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import AOSInitializer from "../components/AOSInitializer";
config.autoAddCss = false



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
        <div
        className="gradient-bg min-h-screen text-gray-300 font-sans antialiased"
      >
        <AOSInitializer>
          {children}
        </AOSInitializer>
      </div>
   
  );
}
